### ISSUE TITLE
For user friendly, need instruction on how to run functional test?

### ISSUE THREAD

**Issue by JuneZhou19** [InfraSIM/infrasim-compute#102]
There is no instruction on how to run functional/unit test. The instruction should include:
1. Precondition. eg. install infrasim all the way until infrasim init, system must be clean which means no ipmi/qemu/socat process runnning.
2. commands to run test.

**Comment by fub2** [comment]
development guide in RTD will have a section to describe that.

**Comment by fub2** [comment]
http://infrasim.readthedocs.io/en/docs-infrasim-compute/dev_guide.html#functional-test
