### ISSUE TITLE
node-0-node fails to start 

### ISSUE THREAD

**Issue by rva818** [InfraSIM/infrasim-compute#115]
**[Problem Description]**
node-0-node fails to start when i run “sudo infrasim-main start” on Ubuntu 16.04.

**[Steps to Reproduce]**
1) Ensure sources.list integrity 
```
$ sudo apt-get update
$ sudo apt-get install python-pip libpython-dev libssl-dev
```

2) Upgrade pip and install setuptools:
```
$ sudo pip install --upgrade pip
$ sudo pip install setuptools
```

3) install infrasim:
```
$ git clone https://github.com/InfraSIM/infrasim-compute.git
$ cd infrasim-compute
$ sudo pip install -r requirements.txt
$ sudo python setup.py install
$ install infrasim from python library:
$ sudo pip install infrasim-compute
```

4)　Start Infrasim Service
```
$ sudo mkdir /etc/qemu
$ sudo infrasim-init
$ sudo infrasim-main start
-> node-0-node fails to start and tcp 5901 does not listen.
```

**[Actual Results]**
Infrasim service starts but node-0-node fails to start and the following messages are displayed.
```
 [ 17629  ] node-0-socat starts to run.
[ 17630  ] node-0-bmc starts to run.
[ ERROR ] node-0-node fail to start
Infrasim service started.
You can access node node-0 via vnc:192.168.18.2:5901 
```

And tcp 5901 does not listen

Operation Log:
[20161018-01.txt](https://github.com/InfraSIM/infrasim-compute/files/535285/20161018-01.txt)

**[Expected Results]**
node-0-socat, node-0-bmc and node-0-node starts and tcp 5901 listens.

**Comment by fub2** [comment]
Anything recorded in /var/log/infrasim/node-0/qemu.log? Were you running virtual machines based  KVM/QEMU? node-0-node is service of qemu vm; there're a couple of reasons it fails in start; one possibility is conflicts - another qemu vm process is running.

http://infrasim.readthedocs.io/en/docs-infrasim-compute/dev_guide.html#logging-and-debugging

**Comment by rva818** [comment]
@fub2  Thank you for your support always.

> Anything recorded in /var/log/infrasim/node-0/qemu.log? 
```
$ cat /var/log/infrasim/node-0/qemu.log
Could not access KVM kernel module: No such file or directory
failed to initialize KVM: No such file or directory
```

From the above, and my infrasim-compute host is running on ESXi, so I operated the following procedure, then node-0-node starts.
1) shutdown infrasim-compute VM
2) Enable “Expose hardware assisted virtualization to the guest OS” of infrasim-compute VM via vSphere Web Client.
3) power-on infrasim-compute VM
4) $ sudo infrasim-main start

Thanks!
