### ISSUE TITLE
Ansible playbook help

### ISSUE THREAD

**Issue by JuneZhou19** [InfraSIM/infrasim-compute#221]
See below message from help,  actually there are 5 commands "node,chassis,config,init,version", why only "init" and "version" have explanation?
--------------------------------------------------------------------------------------------------
$ ansible-playbook -i inventory_example site.yml -t help

PLAY [Install InfraSIM] ********************************************************

TASK [setup] *******************************************************************
ok: [192.168.129.187]

PLAY [Manipulate InfraSIM] *****************************************************

TASK [setup] *******************************************************************
ok: [192.168.129.187]

TASK [commoncmd : Show infrasim CLI help] **************************************
changed: [192.168.129.187]

TASK [commoncmd : debug] *******************************************************
ok: [192.168.129.187] => (item=out.stdout_lines) => {
    "item": "out.stdout_lines",
    "out.stdout_lines": [
        "usage: infrasim [-h] {node,chassis,config,init,version} ...",
        "",
        "optional arguments:",
        "  -h, --help            show this help message and exit",
        "",
        "InfraSIM Commands::",
        "  {node,chassis,config,init,version}",
        "    init                init infrasim environment",
        "    version             check version of infrasim and dependencies"
    ]
}

**Comment by turtle-fly** [comment]
@JuneZhou19 
`infrasim init` is a complete command, `infrasim version` is a complete command as well. Both of them have complete meaning. While `infrasim node`, `infrasim chassis`, `infrasim config` need further options to  make a command. You can get `infrasim node`'s help by enter the incomplete command and see the prompt.

**Comment by JuneZhou19** [comment]
@turtle-fly OK, sounds reasonable.

**Comment by turtle-fly** [comment]
@JuneZhou19 please close this issue
