### ISSUE TITLE
Wrong hint message

### ISSUE THREAD

**Issue by panpan0000** [InfraSIM/infrasim-compute#249]
when I ran
 ```sudo infrasim config add node1 ~/node1.yml ```
it will show hints 
```
Node node1's configuration already in InfraSIM mapping.
If you want to update the configuration, please run this command:
    infrasim **node** update node1 /home/infrasim/node1.yml
```

But it's wrong.
it should provide hint which 
```    infrasim **config** update node1 /home/infrasim/node1.yml```

it should be config instead of node

**Comment by fub2** [comment]
Good catch! Thank you! @WinnieXU1  can you fix it?

**Comment by WinnieXU1** [comment]
ok @fub2

**Comment by fub2** [comment]
Fixed. Closing.
