### ISSUE TITLE
VNC port is user configurable?

### ISSUE THREAD

**Issue by josdotso** [InfraSIM/infrasim-compute#91]
Is there a stanza I can place in infrasim.yml to configure/de-configure VNC?  Starting infrasim compute and I'm not seeing VNC listening on 5901.  :(

**Comment by sharkconi** [comment]
@josdotso Right now, we do not offer the configuration for VNC port. We use the default VNC port 5901.  If you can't see the VNC listening on 5901, make sure the infrasim-compute is running. You  can use 'infrasim-main status' to check whether everything runs successfully.
Thanks

**Comment by josdotso** [comment]
Ok.  Thanks!
