### ISSUE TITLE
How to connect to serial monitor?

### ISSUE THREAD

**Issue by josdotso** [InfraSIM/infrasim-compute#95]
Would like to see iPXE happen in text not VNC format.  I haven't been able to connect to 9003 and see/do anything useful yet.  Any hints you could share on the README?

**Comment by sharkconi** [comment]
@josdotso Sure, you can use ipmitool. The command is "ipmitool -H localhost -I lanplus -U admin -P admin sol activate".
FYI

**Comment by josdotso** [comment]
Great thanks!
